apiVersion: v2
appVersion: "1.1"
description: A Helm chart for Kubernetes
name: webdis
version: 0.2.0
type: application
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
