# Default values for webdis-redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



replicaCount: 1

image:
  repository: anapsix/webdis
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7379

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
  - name: REDIS_HOST
    # update value with "services.namespace"
    value: "rtdb-api-redis-headless.rtdb-api-sorbasoft-net"
  - name: REDIS_PORT
    value: "6379"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  enabled: true
  cluster:
    enabled: true
    slaveCount: 3
  password: null
  usePassword: false
  usePasswordFile: false
